caterwaul.module( 'numeric' ,function($) { (function( ) {var generator=function(base,composite) {;
return function(n,prefix,field) {;
return(function( ) {var f=field||scalar_field,compiled_base=base(n,f) ;
return(rename($.merge( { } ,compiled_base,composite(compiled_base,f) ) ,prefix) ) } ) .call(this) } } ,rename=function(o,prefix) {;
return(function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var x in xs)if(Object.prototype.hasOwnProperty.call(xs,x) )xr[ ( '' + (prefix|| "" ) + '' + (x) + '' ) ] =xs[x] ;
return xr} ) .call(this,o) } ,scalar_field= {zero:ref_h_Kpe3zX8r6h9U$FzfJgfups,one:ref_i_Kpe3zX8r6h9U$FzfJgfups, '+' :ref_j_Kpe3zX8r6h9U$FzfJgfups, '-' :ref_k_Kpe3zX8r6h9U$FzfJgfups, '*' :ref_l_Kpe3zX8r6h9U$FzfJgfups, '/' :ref_m_Kpe3zX8r6h9U$FzfJgfups, 'u~' :ref_n_Kpe3zX8r6h9U$FzfJgfups} ,complex_field= {zero:ref_o_Kpe3zX8r6h9U$FzfJgfups,one:ref_p_Kpe3zX8r6h9U$FzfJgfups, '+' :ref_q_Kpe3zX8r6h9U$FzfJgfups, '-' :ref_r_Kpe3zX8r6h9U$FzfJgfups, '*' :ref_s_Kpe3zX8r6h9U$FzfJgfups, '/' :ref_t_Kpe3zX8r6h9U$FzfJgfups, 'u~' :ref_u_Kpe3zX8r6h9U$FzfJgfups} ,field_rewrite=function(e,field) {;
return(function( ) {var pattern_for=function( /* unary , node */s) {;
return/^\w+$/ .test(s) ?$.parse(s) : /^u/ .test(s) ?$.parse( ( '' + ( (s) .substr( /* unary , node */1) ) + '_x' ) ) :$.parse( ( '_x ' + (s) + ' _y' ) ) } ,patterns= (function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x[0] ,pattern_for(x[0] ) ] ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (field) ) ) ) ) ,visit=function( /* unary , node */node) {;
return(field) .hasOwnProperty( /* unary , node */node.data) ?replace(node,patterns[node.data] ) :node} ,replace=function(n,p) {;
return(function( ) {var template=field[n.data] ,match= (p) .match( /* unary , node */n) ;
return( (template) .replace( /* unary , node */match) ) } ) .call(this) } ;
return( (e) .pmap( /* unary , node */visit) ) } ) .call(this) } ,base_v=function(n,field) {;
return(function( ) {var r=function(n,formals,wrap,fold,each) {;
return(function( ) {var body= (wrap) .replace( /* unary , node */ {x: (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= ( (fold) .replace( /* unary , node */ {x:x0,y:x} ) ) ;
return x0} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (each) .replace( /* unary , node */ {i: ( '' + (x) + '' ) } ) ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (0) , (n) , (1) ) ) ) } ) ,specialized=field_rewrite(body,field) ;
return( (function(it) {return(it.tree=specialized) ,it} ) .call(this, ($.compile( /* unary , node */ (ref_v_Kpe3zX8r6h9U$FzfJgfups) .replace( /* unary , node */ {_formals:formals,_e:specialized} ) ) ) ) ) } ) .call(this) } ;
return( {plus:r(n,ref_x_Kpe3zX8r6h9U$FzfJgfups,ref_y_Kpe3zX8r6h9U$FzfJgfups,ref_z_Kpe3zX8r6h9U$FzfJgfups,ref_10_Kpe3zX8r6h9U$FzfJgfups) ,times:r(n,ref_11_Kpe3zX8r6h9U$FzfJgfups,ref_12_Kpe3zX8r6h9U$FzfJgfups,ref_13_Kpe3zX8r6h9U$FzfJgfups,ref_14_Kpe3zX8r6h9U$FzfJgfups) ,minus:r(n,ref_15_Kpe3zX8r6h9U$FzfJgfups,ref_16_Kpe3zX8r6h9U$FzfJgfups,ref_17_Kpe3zX8r6h9U$FzfJgfups,ref_18_Kpe3zX8r6h9U$FzfJgfups) ,scale:r(n,ref_19_Kpe3zX8r6h9U$FzfJgfups,ref_1a_Kpe3zX8r6h9U$FzfJgfups,ref_1b_Kpe3zX8r6h9U$FzfJgfups,ref_1c_Kpe3zX8r6h9U$FzfJgfups) ,dot:r(n,ref_1d_Kpe3zX8r6h9U$FzfJgfups,ref_1e_Kpe3zX8r6h9U$FzfJgfups,ref_1f_Kpe3zX8r6h9U$FzfJgfups,ref_1g_Kpe3zX8r6h9U$FzfJgfups) ,norm:r(n,ref_1h_Kpe3zX8r6h9U$FzfJgfups,ref_1i_Kpe3zX8r6h9U$FzfJgfups,ref_1j_Kpe3zX8r6h9U$FzfJgfups,ref_1k_Kpe3zX8r6h9U$FzfJgfups) ,macv:r(n,ref_1l_Kpe3zX8r6h9U$FzfJgfups,ref_1m_Kpe3zX8r6h9U$FzfJgfups,ref_1n_Kpe3zX8r6h9U$FzfJgfups,ref_1o_Kpe3zX8r6h9U$FzfJgfups) ,macs:r(n,ref_1p_Kpe3zX8r6h9U$FzfJgfups,ref_1q_Kpe3zX8r6h9U$FzfJgfups,ref_1r_Kpe3zX8r6h9U$FzfJgfups,ref_1s_Kpe3zX8r6h9U$FzfJgfups) } ) } ) .call(this) } ,composite_v=function(base,field) {;
return(function( ) {var ref_compile=function(functions,formals,body) {;
return(function( ) {var specialized=field_rewrite(body,field) ,new_body= (specialized) .replace( /* unary , node */ (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k_b_Kpe3zX8r6h9U$FzfJgfups in xs)if(Object.prototype.hasOwnProperty.call(xs,k_b_Kpe3zX8r6h9U$FzfJgfups) )x=xs[k_b_Kpe3zX8r6h9U$FzfJgfups] ,xr[k_b_Kpe3zX8r6h9U$FzfJgfups] = (new $.ref(x) ) ;
return xr} ) .call(this,functions) ) ;
return( (function(it) {return(it.tree=new_body) ,it} ) .call(this, ($.compile( /* unary , node */ (ref_1t_Kpe3zX8r6h9U$FzfJgfups) .replace( /* unary , node */ {_formals:formals,_e:new_body} ) ) ) ) ) } ) .call(this) } ;
return( {unit:ref_compile(base,ref_1v_Kpe3zX8r6h9U$FzfJgfups,ref_1w_Kpe3zX8r6h9U$FzfJgfups) ,proj:ref_compile(base,ref_1x_Kpe3zX8r6h9U$FzfJgfups,ref_1y_Kpe3zX8r6h9U$FzfJgfups) ,orth:ref_compile(base,ref_1z_Kpe3zX8r6h9U$FzfJgfups,ref_20_Kpe3zX8r6h9U$FzfJgfups) } ) } ) .call(this) } ,base_m=function(n,field) {;
return(function( ) {var componentwise=function( /* unary , node */) {;
return null} ,r3=function( /* unary , node */) {;
return null} ;
return( {plus:componentwise(n,ref_21_Kpe3zX8r6h9U$FzfJgfups,ref_22_Kpe3zX8r6h9U$FzfJgfups) ,scale:componentwise(n,ref_23_Kpe3zX8r6h9U$FzfJgfups,ref_24_Kpe3zX8r6h9U$FzfJgfups) ,minus:componentwise(n,ref_25_Kpe3zX8r6h9U$FzfJgfups,ref_26_Kpe3zX8r6h9U$FzfJgfups) ,transpose:componentwise(n,ref_27_Kpe3zX8r6h9U$FzfJgfups,ref_28_Kpe3zX8r6h9U$FzfJgfups) ,times:r3(n,ref_29_Kpe3zX8r6h9U$FzfJgfups,ref_2a_Kpe3zX8r6h9U$FzfJgfups,ref_2b_Kpe3zX8r6h9U$FzfJgfups,ref_2c_Kpe3zX8r6h9U$FzfJgfups,ref_2d_Kpe3zX8r6h9U$FzfJgfups,ref_2e_Kpe3zX8r6h9U$FzfJgfups,ref_2f_Kpe3zX8r6h9U$FzfJgfups,ref_2g_Kpe3zX8r6h9U$FzfJgfups) } ) } ) .call(this) } ,composite_m=function(base,field) {;
return{ /* unary , node */transpose:null} } ;
return($.linear= {vector:generator(base_v,composite_v) ,matrix:generator(base_m,composite_m) ,scalar_field:scalar_field,complex_field:complex_field} ) } ) .call(this) } ) ;
