// Numeric algorithm compiler | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// This module provides a compiler from array-oriented Caterwaul code to high-performance numerical code. By eliminating memory allocation and array access within loops, the compiled code should
// perform within a factor of two of C code (often within about 25% on the V8 runtime). Unlike most other Caterwaul libraries, this code generator works at runtime rather than at compile-time.
// There are a few reasons for this, the most significant being that the numerical compiler doesn't provide any particular syntactic advantage. It also needs to have function definitions that can
// be resolved at runtime.
// Generated by SDoc 
