caterwaul.module( 'vector' ,function($) { (function( ) {var generator=function(base,composite) {;
return function(n,prefix,field) {;
return(function( ) {var f=field||scalar_field,compiled_base=base(n,f) ;
return(rename($.merge( { } ,compiled_base,composite(compiled_base,f) ) ,prefix) ) } ) .call(this) } } ,rename=function(o,prefix) {;
return(function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var x in xs)if(Object.prototype.hasOwnProperty.call(xs,x) )xr[ ( '' + (prefix|| "" ) + '' + (x) + '' ) ] =xs[x] ;
return xr} ) .call(this,o) } ,compile_function=function(xs,e) {;
return(function(it) {return(it.tree=e) ,it} ) .call(this, ($.compile( /* unary , node */ (ref_h_VxlX9ABVV$cmk32CXSuG1O) .replace( /* unary , node */ {_formals:xs,_e:e} ) ) ) ) } ,scalar_field= {zero:ref_j_VxlX9ABVV$cmk32CXSuG1O,one:ref_k_VxlX9ABVV$cmk32CXSuG1O, '+' :ref_l_VxlX9ABVV$cmk32CXSuG1O, '-' :ref_m_VxlX9ABVV$cmk32CXSuG1O, '*' :ref_n_VxlX9ABVV$cmk32CXSuG1O, '/' :ref_o_VxlX9ABVV$cmk32CXSuG1O, 'u~' :ref_p_VxlX9ABVV$cmk32CXSuG1O} ,complex_field= {zero:ref_q_VxlX9ABVV$cmk32CXSuG1O,one:ref_r_VxlX9ABVV$cmk32CXSuG1O, '+' :ref_s_VxlX9ABVV$cmk32CXSuG1O, '-' :ref_t_VxlX9ABVV$cmk32CXSuG1O, '*' :ref_u_VxlX9ABVV$cmk32CXSuG1O, '/' :ref_v_VxlX9ABVV$cmk32CXSuG1O, 'u~' :ref_w_VxlX9ABVV$cmk32CXSuG1O} ,field_rewrite=function(e,field) {;
return(function( ) {var pattern_for=function( /* unary , node */s) {;
return/^\w+$/ .test(s) ?$.parse(s) : /^u/ .test(s) ?$.parse( ( '' + ( (s) .substr( /* unary , node */1) ) + '_x' ) ) :$.parse( ( '_x ' + (s) + ' _y' ) ) } ,patterns= (function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x[0] ,pattern_for(x[0] ) ] ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (field) ) ) ) ) ,visit=function( /* unary , node */node) {;
return(field) .hasOwnProperty( /* unary , node */node.data) ?replace(node,patterns[node.data] ) :node} ,replace=function(n,p) {;
return(function( ) {var template=field[n.data] ,match= (p) .match( /* unary , node */n) ;
return( (template) .replace( /* unary , node */match) ) } ) .call(this) } ;
return( (e) .pmap( /* unary , node */visit) ) } ) .call(this) } ,v3cross=function( /* unary , node */field) {;
return compile_function(ref_10_VxlX9ABVV$cmk32CXSuG1O) } ,base_v=function(n,field) {;
return(function( ) {var r=function(n,formals,wrap,fold,each) {;
return(function( ) {var body= (wrap) .replace( /* unary , node */ {x: (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= ( (fold) .replace( /* unary , node */ {x:x0,y:x} ) ) ;
return x0} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (each) .replace( /* unary , node */ {i: ( '' + (x) + '' ) } ) ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (0) , (n) , (1) ) ) ) } ) ,specialized=field_rewrite(body,field) ;
return(compile_function(formals,specialized) ) } ) .call(this) } ;
return( {plus:r(n,ref_11_VxlX9ABVV$cmk32CXSuG1O,ref_12_VxlX9ABVV$cmk32CXSuG1O,ref_13_VxlX9ABVV$cmk32CXSuG1O,ref_14_VxlX9ABVV$cmk32CXSuG1O) ,times:r(n,ref_15_VxlX9ABVV$cmk32CXSuG1O,ref_16_VxlX9ABVV$cmk32CXSuG1O,ref_17_VxlX9ABVV$cmk32CXSuG1O,ref_18_VxlX9ABVV$cmk32CXSuG1O) ,minus:r(n,ref_19_VxlX9ABVV$cmk32CXSuG1O,ref_1a_VxlX9ABVV$cmk32CXSuG1O,ref_1b_VxlX9ABVV$cmk32CXSuG1O,ref_1c_VxlX9ABVV$cmk32CXSuG1O) ,scale:r(n,ref_1d_VxlX9ABVV$cmk32CXSuG1O,ref_1e_VxlX9ABVV$cmk32CXSuG1O,ref_1f_VxlX9ABVV$cmk32CXSuG1O,ref_1g_VxlX9ABVV$cmk32CXSuG1O) ,dot:r(n,ref_1h_VxlX9ABVV$cmk32CXSuG1O,ref_1i_VxlX9ABVV$cmk32CXSuG1O,ref_1j_VxlX9ABVV$cmk32CXSuG1O,ref_1k_VxlX9ABVV$cmk32CXSuG1O) ,norm:r(n,ref_1l_VxlX9ABVV$cmk32CXSuG1O,ref_1m_VxlX9ABVV$cmk32CXSuG1O,ref_1n_VxlX9ABVV$cmk32CXSuG1O,ref_1o_VxlX9ABVV$cmk32CXSuG1O) ,macv:r(n,ref_1p_VxlX9ABVV$cmk32CXSuG1O,ref_1q_VxlX9ABVV$cmk32CXSuG1O,ref_1r_VxlX9ABVV$cmk32CXSuG1O,ref_1s_VxlX9ABVV$cmk32CXSuG1O) ,macs:r(n,ref_1t_VxlX9ABVV$cmk32CXSuG1O,ref_1u_VxlX9ABVV$cmk32CXSuG1O,ref_1v_VxlX9ABVV$cmk32CXSuG1O,ref_1w_VxlX9ABVV$cmk32CXSuG1O) } ) } ) .call(this) } ,composite_v=function(base,field) {;
return(function( ) {var ref_compile=function(functions,formals,body) {;
return(function( ) {var specialized=field_rewrite(body,field) ,new_body= (specialized) .replace( /* unary , node */ (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k_b_VxlX9ABVV$cmk32CXSuG1O in xs)if(Object.prototype.hasOwnProperty.call(xs,k_b_VxlX9ABVV$cmk32CXSuG1O) )x=xs[k_b_VxlX9ABVV$cmk32CXSuG1O] ,xr[k_b_VxlX9ABVV$cmk32CXSuG1O] = (new $.ref(x) ) ;
return xr} ) .call(this,functions) ) ;
return(compile_function(formals,new_body) ) } ) .call(this) } ;
return( {unit:ref_compile(base,ref_1x_VxlX9ABVV$cmk32CXSuG1O,ref_1y_VxlX9ABVV$cmk32CXSuG1O) ,proj:ref_compile(base,ref_1z_VxlX9ABVV$cmk32CXSuG1O,ref_20_VxlX9ABVV$cmk32CXSuG1O) ,orth:ref_compile(base,ref_21_VxlX9ABVV$cmk32CXSuG1O,ref_22_VxlX9ABVV$cmk32CXSuG1O) } ) } ) .call(this) } ;
return($.vector=$.merge(generator(base_v,composite_v) , {scalar_field:scalar_field,complex_field:complex_field,v3cross:v3cross} ) ) } ) .call(this) } ) ;
